# Project configuration
general:
  productiveBranch: 'main'
# Stage configuration
stages:
  productionDeployment:
    cfTargets:
      - org: '2f05827ftrial'
        space: 'dev'
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        appName: 'csm-demo-202002-actuals-cap-srv'
        credentialsId: 'cfdeploy'
